name: Manually trigger an Azure Machine Learning job

on:
  workflow_dispatch:

jobs:
  train:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repo
      uses: actions/checkout@main
    - name: Install az ml extension
      run: az extension add -n ml -y
    - name: Azure login
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}
    - name: Training model
      code: model
      command: >-
        python train.py
        --diabetes ${{inputs.diabetes}}
        --reg_rate ${{inputs.reg_rate}}
      inputs:
        diabetes:
          type: uri_folder 
          path: azureml:diabetes-dev-folder2:1
        reg_rate: 0.01
      environment: azureml:AzureML-sklearn-0.24-ubuntu18.04-py37-cpu@latest
      compute: azureml:testdev-vm22
      experiment_name: diabetes-data-example
      description: Train a classification model on diabetes data using a registered dataset as input.
